# Generated by Django 3.2.19 on 2023-05-17 04:05

import django.core.validators
from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imageses',
            field=models.ImageField(blank=True, default='', upload_to=main.utilities.get_timestamp_path, verbose_name=' Доп Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo_file',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=main.utilities.get_timestamp_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp'])]),
        ),
    ]
